- after https://github.com/apache/cassandra/commit/dc17c29724d86547538cc8116ff1a90d36a0bf3a,   4.1.6 branch is broken. fix LuceneStorageProxy.java
Unexpected exception during request; channel = [id: 0xf3b04ed5, L:/172.19.138.44:9042 - R:/172.19.133.25:51606]
java.lang.NoClassDefFoundError: org.apache.cassandra.service.LuceneStorageProxy (initialization failure)
    at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:166)
    at com.stratio.cassandra.lucene.IndexPagingState.update(IndexPagingState.scala:152)
    ...
    at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:142)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:839)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.cassandra.service.StorageProxy.fetchRows(java.util.List, org.apache.cassandra.db.ConsistencyLevel, long)
    at org.apache.cassandra.service.LuceneStorageProxy.<clinit>(LuceneStorageProxy.java:59)
    ... 22 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.apache.cassandra.service.StorageProxy.fetchRows(java.util.List, org.apache.cassandra.db.ConsistencyLevel, long)
    at java.base/java.lang.Class.newNoSuchMethodException(Class.java:649)
    at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1449)
    ...